### ISSUE TITLE
Investigate if possibile to boot any kernel with modules (not built in by default)

### ISSUE THREAD

**Issue by jcvenegas** [kata-containers/packaging#298]
Today in Kata we request to a a set of features enabled by default as built-in 

 - virtio-9pfs
 - virtio-net
 - virtio-serial

For some use cases an user may want to use the host kernel, that has the modules enabled but not built-in.

Lets find a way to reduce the amount of features needed to boot a generic kernel.

For example:

- The kernel boots
- Connect runtime with agent using serial port ( grpc over serial ) serial may be a requeriment
- Let the agent ask for modules it needs
- Use CopyFile grpc call  to pass modules needed
- Make the agent do modprobe modules provided from host.
- Finish boot

The modules that may be passed are 9pfs-virtio (or the any module used to share files with Kata container, like virtio-fs)

/cc @lsm5 probably needed for Fedora, as it only maintains one kernel with virtualization features as module, not build in and probably only one package is not a reason to convert a kernel module to built-in.

/cc @stefanha as he already being playing with this approach for Kata using systemd.

Notes:

 - It would be great  to make the kernel do not dependent on the kata rootfs.
This mean, this would be to avoid regenerate a rootfs every time new kernel is used.
 -  If is not possible to make independent the image and the kernel then try to reduce the amount of modules copied to the image/initrd to avoid make them too big.

\cc @sboeuf @jodh-intel @egernst

**Comment by sboeuf** [comment]
@jcvenegas this proposal is a valid concern IMO, but I'm worried the solution using `CopyFile()` might increase the boot time of our containers depending on the size of the modules. And also, this will increase the code complexity for a limited gain (the gain being to simplify the life of our users by not having to modify the rootfs themselves).

**Comment by stefanha** [comment]
> /cc @stefanha as he already being playing with this approach for Kata using systemd.

For the record, my approach was to build a Fedora rootfs, including kernel modules, into an initramfs.  Kata launched the kernel + initramfs.  I didn't try copying kernel modules on-demand.

**Comment by stefanha** [comment]
> @jcvenegas this proposal is a valid concern IMO, but I'm worried the solution using `CopyFile()` might increase the boot time of our containers depending on the size of the modules. And also, this will increase the code complexity for a limited gain (the gain being to simplify the life of our users by not having to modify the rootfs themselves).

The challenge for distros packaging Kata is to deliver ready-to-go packages.  Users want to install the packages and immediately launch containers without first learning how Kata fits together or how to build a rootfs.

The current approach with the rootfs builder scripts has worked well for developers and early adopters, but it isn't convenient enough for the broader userbase.

Additionally, distros ship kernel updates periodically.  Each time the kernel is changed the rootfs becomes obsolete since /lib/modules will be outdated.  Users shouldn't need to go back and rebuild the rootfs.  The process also takes a significant amount of time (minutes on my system) and is therefore not suitable for inclusion in package update scripts.

I think @jcvenegas goal is to solve these problems so that distros can ship ready-to-go Kata packages that just work across kernel updates and do not create extra work for distro kernel package maintainers.

I also share @sboeuf's concerns that copying in modules is slow.  That would need to be measured.

Also, kata-agent itself requires kernel modules like virtio-serial before it can start up.  It also requires networking for the network-related agent commands.  So I'm not sure if we can easily send over modules via the agent.

@jcvenegas what happened to your idea for concatenating initramfs cpio archives?  I thought that was promising: an immutable core rootfs + a /lib/modules cpio archive that gets updated more frequently.

**Comment by jcvenegas** [comment]
@sboeuf the limited gain probably is not a lot for most of our workflow, but is necessary to increase the adoption specially on Linux distributions, some distros has strong policy about create new kernel flavors.

I had the idea that qemu supported to use -initrd 'cpio1, cpio2' and provide it to the kernel for an rootfs. This stop me to conitnue for a moment. But now I have working progress script that does the following.

- Create cpio with modules needed by kata: `9pfs`, `virtio-console`, `vitio-net`, as you mention uses set in the proper directory (`/lib/modules/$(uname -r)`)
 a. Probably is better to not limit this to uname -r and take all the exiting kernel variants.
- Given an exiting `immutable core rootfs` and a `/lib/modules cpio` it is merged into a new one.
 a. This way the rootfs with the agent is not generated all the times that the kernel changes.

Now the question is where and how will be trigger the process to create a cpio merged with modules.
     a. Add a kernel subpackage on that triggers this rebuild of a cpio file with the modules for kata.

     b. Add the logic on the kata runtime: add to the configuration.toml `kernel_module_cpio=path`
```
previous_sha=store.Get("kernel_module_cpio")
modules_sha=sha(kernel_module_cpio)
// cpio changed 
if modules_sha != previous_sha {
     previous_sha=store.Save("kernel_module_cpio", modules_sha)
     merget_cpio=(initrd, kernel_module_cpio)
     // conitnue boot with merget_cpio ... that has the modules updated
}
```
the configuration.toml would like like
```toml
[hypervisor.qemu]
path = "/usr/bin/qemu-system-x86_64"
# path to cpio generated on new kernel install or update
# this cpio file contain modules need by kata
# it is merged with initrd to boot the kata VM
kernel_module_cpio = "/usr/share/kata-containers/kernel-modules.cpio" 
# sylink to latest kernel installed kernel
kernel = "/usr/share/kata-containers/vmlinuz.container" 
# symlink to latest kata rootfs
initrd = "/usr/share/kata-containers/kata-containers.init" 

machine_type = "pc"

```
```

**Comment by jcvenegas** [comment]
@sboeuf the limited gain probably is not a lot for most of our workflow, but is necessary to increase the adoption specially on Linux distributions, some distros has strong policy about create new kernel flavors.

I had the idea that qemu supported to use -initrd 'cpio1, cpio2' and provide it to the kernel for an rootfs. This stop me to conitnue for a moment. But now I have working progress script that does the following.

- Create cpio with modules needed by kata: `9pfs`, `virtio-console`, `vitio-net`, as you mention uses set in the proper directory (`/lib/modules/$(uname -r)`)
 a. Probably is better to not limit this to uname -r and take all the exiting kernel variants.
- Given an exiting `immutable core rootfs` and a `/lib/modules cpio` it is merged into a new one.
 a. This way the rootfs with the agent is not generated all the times that the kernel changes.

Now the question is where and how will be trigger the process to create a cpio merged with modules.
     a. Add a kernel subpackage on that triggers this rebuild of a cpio file with the modules for kata.

     b. Add the logic on the kata runtime: add to the configuration.toml `kernel_module_cpio=path`
```
previous_sha=store.Get("kernel_module_cpio")
modules_sha=sha(kernel_module_cpio)
// cpio changed 
if modules_sha != previous_sha {
     previous_sha=store.Save("kernel_module_cpio", modules_sha)
     merget_cpio=(initrd, kernel_module_cpio)
     // conitnue boot with merget_cpio ... that has the modules updated
}
```
the configuration.toml would like like
```toml
[hypervisor.qemu]
path = "/usr/bin/qemu-system-x86_64"
# path to cpio generated on new kernel install or update
# this cpio file contain modules need by kata
# it is merged with initrd to boot the kata VM
kernel_module_cpio = "/usr/share/kata-containers/kernel-modules.cpio" 
# sylink to latest kernel installed kernel
kernel = "/usr/share/kata-containers/vmlinuz.container" 
# symlink to latest kata rootfs
initrd = "/usr/share/kata-containers/kata-containers.init" 

machine_type = "pc"

```
```
