### ISSUE TITLE
1.13 runtimeClass definitions are broken

### ISSUE THREAD

**Issue by egernst** [kata-containers/packaging#560]
# Description of problem

It looks like 1.13 and 1.14 example are identical, save the apiVersion.  In reality, the field itself changed - 1.13 had a spec, which was removed in 1.14.

1.13 should be something like below:
```yaml
---
kind: RuntimeClass
apiVersion: node.k8s.io/v1alpha1
metadata:
    name: kata-qemu
spec:
    runtimeHandler: kata-qemu
```

Similarly, we should add the runtimeclass_crd, which was also needed in 1.13:
```yaml
kind: CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1beta1
metadata:
  name: runtimeclasses.node.k8s.io
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  group: node.k8s.io
  version: v1alpha1
  versions:
    - name: v1alpha1
      served: true
      storage: true
  names:
    plural:   runtimeclasses
    singular: runtimeclass
    kind:     RuntimeClass
  scope: Cluster
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            runtimeHandler:
              type: string
              pattern: '^([a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)?$'
```
