### ISSUE TITLE
Create Linux kernel configuration script

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/packaging#8]
As @sameo noted in https://github.com/kata-containers/linux/pull/5#issuecomment-366935051, we should have a script that can generate a valid kernel configuration file.

The script will generate a valid `.config` kernel configuration file to be used by the kernel's build system.

However, the script will allow individual options and groups of options to be documented as the kernel's config file does not support comments (well, it does, but only for "commented out" / disabled `CONFIG_` options).

Each group of config options in the script should document:

- Why it has been enabled.
- If there is any known impact (positive or negative) on boot speed / general performance.
- If there is any known impact (positive or negative) on memory density.

See also: #7.

**Comment by jodh-intel** [comment]
I was imagining a script that would do something similar to https://github.com/kata-containers/packaging/blob/master/scripts/configure-hypervisor.sh. The script would read a YAML config file and would create a (partial) `.config` file. You could then run `make olddefconfig` so that Kconfig would add in any missing `CONFIG_*` options and (hopefully?) generate a usable kernel.

The config file would be something like the following (in pseudo-YAML):

```
config:
    CONFIG_FOO:
      type: [module|built-in|disabled]
      reasons: [boot-speed|memory-density|security]
      architectures: all
      notes: free-form multi-line text to describe the option goes here.

  CONFIG_BAR:
      ...

  CONFIG_BAZ:
      ...
```

The config file would not list all config options - it would only list those that we have to set or explicitly disable. However, I don't know whether such a plan would even work.

Any thoughts @grahamwhaley, @sboeuf, @bergwolf?
