### ISSUE TITLE
kata-deploy: replacement of crio runtime paths could be more clever

### ISSUE THREAD

**Issue by grahamwhaley** [kata-containers/packaging#928]
# Description of problem

It looks like kata runtime entries are now in the upstream `crio.conf` by default, but commented out. I think this is defeating our sed replacement magic, and ends up with us adding our new runtime path in .... to the existing commented out line.

# Details

The [crio.conf file now contains kata entries](https://github.com/cri-o/cri-o/blob/master/pkg/config/template.go#L277-L288), that end up looking like this in the minikube crio.conf:

```toml
# Kata Containers is an OCI runtime, where containers are run inside lightweight
# VMs. Kata provides additional isolation towards the host, minimizing the host attack
# surface and mitigating the consequences of containers breakout.
                                                                            
# Kata Containers with the default configured VMM                          
#[crio.runtime.runtimes.kata-runtime]

# Kata Containers with the QEMU VMM                          
#[crio.runtime.runtimes.kata-qemu]                                
                   
# Kata Containers with the Firecracker VMM
#[crio.runtime.runtimes.kata-fc]
```

Our [kata-deploy.sh tries to edit/add like this](https://github.com/kata-containers/packaging/blob/master/kata-deploy/scripts/kata-deploy.sh#L83-L92):

```bash
	local kata_qemu_path="/opt/kata/bin/kata-qemu"
	local kata_qemu_conf="crio.runtime.runtimes.kata-qemu"

	local kata_qemu_virtiofs_path="/opt/kata/bin/kata-qemu-virtiofs"
	local kata_qemu_virtiofs_conf="crio.runtime.runtimes.kata-qemu-virtiofs"

	# add kata-qemu config
	if grep -q "\[$kata_qemu_conf\]" $crio_conf_file; then
		echo "Configuration exists $kata_qemu_conf, overwriting"
		sed -i "/\[$kata_qemu_conf\]/,+1s#runtime_path.*#runtime_path = \"${kata_qemu_path}\"#" $crio_conf_file
```

deploying the kata-deploy.yaml, the log looks like:

```
copying kata artifacts onto host
Add Kata Containers as a supported runtime for CRIO:
Configuration exists crio.runtime.runtimes.kata-qemu, overwriting

# Path to the Kata Containers runtime binary that uses the QEMU hypervisor with virtiofs support.
[crio.runtime.runtimes.kata-qemu-virtiofs]
  runtime_path = "/opt/kata/bin/kata-qemu-virtiofs"
Configuration exists for crio.runtime.runtimes.kata-fc, overwriting

# Path to the Kata Containers runtime binary that uses the Cloud Hypervisor.
[crio.runtime.runtimes.kata-clh]
  runtime_path = "/opt/kata/bin/kata-clh"
node/minikube labeled
```

and the `crio.conf` then looks like:

```toml
# Kata Containers is an OCI runtime, where containers are run inside lightweight
# VMs. Kata provides additional isolation towards the host, minimizing the host attack
# surface and mitigating the consequences of containers breakout.                                
                                                                               
# Kata Containers with the default configured VMM  
#[crio.runtime.runtimes.kata-runtime]
                                                                            
# Kata Containers with the QEMU VMM                                                              
#[crio.runtime.runtimes.kata-qemu]                                              
                                                                                      
# Kata Containers with the Firecracker VMM                       
#[crio.runtime.runtimes.kata-fc]        

.... lots of other stuff....
# Path to the Kata Containers runtime binary that uses the QEMU hypervisor with virtiofs support.
[crio.runtime.runtimes.kata-qemu-virtiofs]                                     
  runtime_path = "/opt/kata/bin/kata-qemu-virtiofs"
                                     
# Path to the Kata Containers runtime binary that uses the Cloud Hypervisor.
[crio.runtime.runtimes.kata-clh]                                                                 
  runtime_path = "/opt/kata/bin/kata-clh"        
```

The problem is, that `kata-qemu` is still commented out :-(, and does not have a `runtime_path` line, so trying to deploy the example `kata-qemu` nginx from the `kata-deploy` pages fails... runtime not found.

We probably need to be smarter with the grep etc. I guess we could:
- uncomment the line if we find it commented out
- ignore the line if it is not enabled already

I favour the second option, likely by changing the grep search pattern to more like `"$\[$kata_qemu_conf\]"`.

# Related

We fixed it differently for our CI installer afaict at https://github.com/kata-containers/tests/pull/2057

This is affecting minikube right now, as seen at: https://github.com/kata-containers/documentation/issues/448#issuecomment-574896969
